// Factory materials catalogue for Yıldız Entegre (MDFLAM / Suntalam / Kapak Panel).
// Sheet dimensions: MDFLAM 2100 × 2800 mm, Kapak Panel 1220 × 2800 mm.
export const YILDIZ_CATALOG_PRESETS = [
  {
    "id": "yildiz-yt-z75-18",
    "name": "Yıldız MDFLAM · Crystal Onyx YT_Z75 · 18 мм",
    "type": "MDFLAM",
    "color": "#deddd9",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z75",
    "sourceUrl": "https://www.yildizentegre.com/en/products/panel"
  },
  {
    "id": "yildiz-yt-z72-18",
    "name": "Yıldız MDFLAM · Aura Marble YT_Z72 · 18 мм",
    "type": "MDFLAM",
    "color": "#deddd9",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z72",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/aura-marble-yt-z72"
  },
  {
    "id": "yildiz-yt-z71-18",
    "name": "Yıldız MDFLAM · Linen Chevron YT_Z71 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z71",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/linen-chevron-yt-z71"
  },
  {
    "id": "yildiz-yt-z76-18",
    "name": "Yıldız MDFLAM · Salda Beige YT_Z76 · 18 мм",
    "type": "MDFLAM",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z76",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/salda-beige-yt-z76"
  },
  {
    "id": "yildiz-yt-z73-18",
    "name": "Yıldız MDFLAM · Peak Marble YT_Z73 · 18 мм",
    "type": "MDFLAM",
    "color": "#deddd9",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z73",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/peak-marble-yt-z73"
  },
  {
    "id": "yildiz-yt-z74-18",
    "name": "Yıldız MDFLAM · Vero Walnut YT_Z74 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z74",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/vero-walnut-yt-z74"
  },
  {
    "id": "yildiz-yt-10z-18",
    "name": "Yıldız MDFLAM · Saturn Beige YT_10Z · 18 мм",
    "type": "MDFLAM",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_10Z",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/saturn-beige-yt-10z"
  },
  {
    "id": "yildiz-yt-10v-18",
    "name": "Yıldız MDFLAM · Mocha Coffee YT_10V · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_10V",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/mocha-coffee-yt-10v"
  },
  {
    "id": "yildiz-yt-10u-18",
    "name": "Yıldız MDFLAM · Linden Green YT_10U · 18 мм",
    "type": "MDFLAM",
    "color": "#5d7362",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_10U",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/linden-green-yt-10u"
  },
  {
    "id": "yildiz-yt-10t-18",
    "name": "Yıldız MDFLAM · Mystic Plum YT_10T · 18 мм",
    "type": "MDFLAM",
    "color": "#7d383b",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_10T",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/mystic-plum-yt-10t"
  },
  {
    "id": "yildiz-yt-10s-18",
    "name": "Yıldız MDFLAM · Zen Travertene YT_10S · 18 мм",
    "type": "MDFLAM",
    "color": "#deddd9",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_10S",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/zen-travertene-yt-10s"
  },
  {
    "id": "yildiz-yt-10h-18",
    "name": "Yıldız MDFLAM · Cherry Marble YT_10H · 18 мм",
    "type": "MDFLAM",
    "color": "#deddd9",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_10H",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/cherry-marble-yt-10h"
  },
  {
    "id": "yildiz-yt-10f-18",
    "name": "Yıldız MDFLAM · Sahara Oak YT_10F · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_10F",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/sahara-oak-yt-10f"
  },
  {
    "id": "yildiz-yt-11e-18",
    "name": "Yıldız MDFLAM · Spike Oak YT_11E · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_11E",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/spike-oak-yt-11e"
  },
  {
    "id": "yildiz-yt-10r-18",
    "name": "Yıldız MDFLAM · Amber Walnut YT_10R · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_10R",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/amber-walnut-yt-10r"
  },
  {
    "id": "yildiz-yt-10g-18",
    "name": "Yıldız MDFLAM · Bergamo Walnut YT_10G · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_10G",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/bergamo-walnut-yt-10g"
  },
  {
    "id": "yildiz-vt-348-18",
    "name": "Yıldız MDFLAM · Ultra White VT_348 · 18 мм",
    "type": "MDFLAM",
    "color": "#f0f0eb",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_348",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/ultra-white-vt-348"
  },
  {
    "id": "yildiz-vt-998-18",
    "name": "Yıldız MDFLAM · M-White VT_998 · 18 мм",
    "type": "MDFLAM",
    "color": "#f0f0eb",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_998",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/m-white-vt-998"
  },
  {
    "id": "yildiz-vt-568-18",
    "name": "Yıldız MDFLAM · Pearl Cream VT_568 · 18 мм",
    "type": "MDFLAM",
    "color": "#f1ede2",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_568",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/pearl-cream-vt-568"
  },
  {
    "id": "yildiz-vt-010-18",
    "name": "Yıldız MDFLAM · Beige VT_010 · 18 мм",
    "type": "MDFLAM",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_010",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/beige-vt-010"
  },
  {
    "id": "yildiz-vt-144-18",
    "name": "Yıldız MDFLAM · Cream VT_144 · 18 мм",
    "type": "MDFLAM",
    "color": "#f1ede2",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_144",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/cream-vt-144"
  },
  {
    "id": "yildiz-vt-265-18",
    "name": "Yıldız MDFLAM · Vario Mink VT_265 · 18 мм",
    "type": "MDFLAM",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_265",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/vario-mink-vt-265"
  },
  {
    "id": "yildiz-yt-73a-18",
    "name": "Yıldız MDFLAM · Mozambique YT_73A · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_73A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/panel"
  },
  {
    "id": "yildiz-vt-969-18",
    "name": "Yıldız MDFLAM · Office Grey VT_969 · 18 мм",
    "type": "MDFLAM",
    "color": "#c4c6c5",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_969",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/office-grey-vt-969"
  },
  {
    "id": "yildiz-vt-237-18",
    "name": "Yıldız MDFLAM · Grey VT_237 · 18 мм",
    "type": "MDFLAM",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_237",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/grey-vt-237"
  },
  {
    "id": "yildiz-vt-828-18",
    "name": "Yıldız MDFLAM · Mist Grey VT_828 · 18 мм",
    "type": "MDFLAM",
    "color": "#c4c6c5",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_828",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/mist-grey-vt-828"
  },
  {
    "id": "yildiz-yt-26d-18",
    "name": "Yıldız MDFLAM · Velvet Gray YT_26D · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_26D",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/velvet-gray-yt-26d"
  },
  {
    "id": "yildiz-vt-505-18",
    "name": "Yıldız MDFLAM · Ash Grey VT_505 · 18 мм",
    "type": "MDFLAM",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_505",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/ash-grey-vt-505"
  },
  {
    "id": "yildiz-vt-824-18",
    "name": "Yıldız MDFLAM · Desert Beige VT_824 · 18 мм",
    "type": "MDFLAM",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_824",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/desert-beige-vt-824"
  },
  {
    "id": "yildiz-yt-z65-18",
    "name": "Yıldız MDFLAM · Pebble YT_Z65 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z65",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/pebble-yt-z65"
  },
  {
    "id": "yildiz-vt-538-18",
    "name": "Yıldız MDFLAM · Sand Beige VT_538 · 18 мм",
    "type": "MDFLAM",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_538",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/sand-beige-vt-538"
  },
  {
    "id": "yildiz-yt-z64-18",
    "name": "Yıldız MDFLAM · Pearly Sand YT_Z64 · 18 мм",
    "type": "MDFLAM",
    "color": "#f1ede2",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z64",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/pearly-sand-yt-z64"
  },
  {
    "id": "yildiz-vt-823-18",
    "name": "Yıldız MDFLAM · Selenit VT_823 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_823",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/selenit-vt-823"
  },
  {
    "id": "yildiz-vt-651-18",
    "name": "Yıldız MDFLAM · Sahara VT_651 · 18 мм",
    "type": "MDFLAM",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_651",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/sahara-vt-651"
  },
  {
    "id": "yildiz-vt-278-18",
    "name": "Yıldız MDFLAM · Cappuccino VT_278 · 18 мм",
    "type": "MDFLAM",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_278",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/cappuccino-vt-278"
  },
  {
    "id": "yildiz-yt-z42-18",
    "name": "Yıldız MDFLAM · Izola YT_Z42 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z42",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/izola-yt-z42"
  },
  {
    "id": "yildiz-vt-459-18",
    "name": "Yıldız MDFLAM · Earth VT_459 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_459",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/earth-vt-459"
  },
  {
    "id": "yildiz-yt-74a-18",
    "name": "Yıldız MDFLAM · Barbados YT_74A · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_74A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/barbados-yt-74a"
  },
  {
    "id": "yildiz-yt-85b-18",
    "name": "Yıldız MDFLAM · Vita YT_85B · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_85B",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/vita-yt-85b"
  },
  {
    "id": "yildiz-vt-829-18",
    "name": "Yıldız MDFLAM · Carbon Grey VT_829 · 18 мм",
    "type": "MDFLAM",
    "color": "#303433",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_829",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/carbon-grey-vt-829"
  },
  {
    "id": "yildiz-vt-285-18",
    "name": "Yıldız MDFLAM · Dark Grey VT_285 · 18 мм",
    "type": "MDFLAM",
    "color": "#4a4d4f",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_285",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/dark-grey-vt-285"
  },
  {
    "id": "yildiz-vt-728-18",
    "name": "Yıldız MDFLAM · Melissa VT_728 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_728",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/melissa-vt-728"
  },
  {
    "id": "yildiz-vt-826-18",
    "name": "Yıldız MDFLAM · Geranium VT_826 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_826",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/geranium-vt-826"
  },
  {
    "id": "yildiz-yt-z41-18",
    "name": "Yıldız MDFLAM · Dubrovnik YT_Z41 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z41",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/dubrovnik-yt-z41"
  },
  {
    "id": "yildiz-yt-88b-18",
    "name": "Yıldız MDFLAM · Silva YT_88B · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_88B",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/silva-yt-88b"
  },
  {
    "id": "yildiz-yt-34d-18",
    "name": "Yıldız MDFLAM · Baroque Blue YT_34D · 18 мм",
    "type": "MDFLAM",
    "color": "#4b6982",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_34D",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/baroque-blue-yt-34d"
  },
  {
    "id": "yildiz-yt-35d-18",
    "name": "Yıldız MDFLAM · Atlas Blue YT_35D · 18 мм",
    "type": "MDFLAM",
    "color": "#4b6982",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_35D",
    "sourceUrl": "https://www.yildizentegre.com/en/products/panel"
  },
  {
    "id": "yildiz-vt-025-18",
    "name": "Yıldız MDFLAM · Blue VT_025 · 18 мм",
    "type": "MDFLAM",
    "color": "#4b6982",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_025",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/blue-vt-025"
  },
  {
    "id": "yildiz-yt-01h-18",
    "name": "Yıldız MDFLAM · Cobalt Blue YT_01H · 18 мм",
    "type": "MDFLAM",
    "color": "#4b6982",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_01H",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/cobalt-blue-yt-01h"
  },
  {
    "id": "yildiz-yt-33d-18",
    "name": "Yıldız MDFLAM · Coral Red YT_33D · 18 мм",
    "type": "MDFLAM",
    "color": "#7d383b",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_33D",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/coral-red-yt-33d"
  },
  {
    "id": "yildiz-yt-28d-18",
    "name": "Yıldız MDFLAM · Agate Red YT_28D · 18 мм",
    "type": "MDFLAM",
    "color": "#7d383b",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_28D",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/agate-red-yt-28d"
  },
  {
    "id": "yildiz-vt-019-18",
    "name": "Yıldız MDFLAM · Red VT_019 · 18 мм",
    "type": "MDFLAM",
    "color": "#7d383b",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_019",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/red-vt-019"
  },
  {
    "id": "yildiz-vt-032-18",
    "name": "Yıldız MDFLAM · Orange VT_032 · 18 мм",
    "type": "MDFLAM",
    "color": "#b89758",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_032",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/orange-vt-032"
  },
  {
    "id": "yildiz-yt-10j-18",
    "name": "Yıldız MDFLAM · Tan YT_10J · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_10J",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/tan-yt-10j"
  },
  {
    "id": "yildiz-yt-57a-18",
    "name": "Yıldız MDFLAM · Rosette YT_57A · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_57A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/rosette-yt-57a"
  },
  {
    "id": "yildiz-vt-449-18",
    "name": "Yıldız MDFLAM · Pink Dream VT_449 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_449",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/pink-dream-vt-449"
  },
  {
    "id": "yildiz-vt-384-18",
    "name": "Yıldız MDFLAM · Metallic Pearl VT_384 · 18 мм",
    "type": "MDFLAM",
    "color": "#f1ede2",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_384",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/metallic-pearl-vt-384"
  },
  {
    "id": "yildiz-vt-362-18",
    "name": "Yıldız MDFLAM · Metallic Ecru VT_362 · 18 мм",
    "type": "MDFLAM",
    "color": "#f1ede2",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_362",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/metallic-ecru-vt-362"
  },
  {
    "id": "yildiz-vt-344-18",
    "name": "Yıldız MDFLAM · Metallic Grey VT_344 · 18 мм",
    "type": "MDFLAM",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_344",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/metallic-grey-vt-344"
  },
  {
    "id": "yildiz-yt-36c-18",
    "name": "Yıldız MDFLAM · Metallic Anthracite YT_36C · 18 мм",
    "type": "MDFLAM",
    "color": "#4a4d4f",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_36C",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/metallic-anthracite-yt-36c"
  },
  {
    "id": "yildiz-vt-11a-18",
    "name": "Yıldız MDFLAM · Venus VT_11A · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_11A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/venus-vt-11a"
  },
  {
    "id": "yildiz-vt-303-18",
    "name": "Yıldız MDFLAM · Metallic Brown VT_303 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_303",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/metallic-brown-vt-303"
  },
  {
    "id": "yildiz-vt-297-18",
    "name": "Yıldız MDFLAM · Cotton Grey VT_297 · 18 мм",
    "type": "MDFLAM",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_297",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/cotton-grey-vt-297"
  },
  {
    "id": "yildiz-vt-549-18",
    "name": "Yıldız MDFLAM · Cotton Beige VT_549 · 18 мм",
    "type": "MDFLAM",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_549",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/cotton-beige-vt-549"
  },
  {
    "id": "yildiz-yt-98d-18",
    "name": "Yıldız MDFLAM · Latte Mink YT_98D · 18 мм",
    "type": "MDFLAM",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_98D",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/latte-mink-yt-98d"
  },
  {
    "id": "yildiz-vt-298-18",
    "name": "Yıldız MDFLAM · Cotton Brown VT_298 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_298",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/cotton-brown-vt-298"
  },
  {
    "id": "yildiz-vt-592-18",
    "name": "Yıldız MDFLAM · Grey Chevron VT_592 · 18 мм",
    "type": "MDFLAM",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_592",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/grey-chevron-vt-592"
  },
  {
    "id": "yildiz-vt-555-18",
    "name": "Yıldız MDFLAM · Chevron VT_555 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_555",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/chevron-vt-555"
  },
  {
    "id": "yildiz-yt-z37-18",
    "name": "Yıldız MDFLAM · Verga YT_Z37 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z37",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/verga-yt-z37"
  },
  {
    "id": "yildiz-yt-z36-18",
    "name": "Yıldız MDFLAM · Piran YT_Z36 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z36",
    "sourceUrl": "https://www.yildizentegre.com/en/products/panel"
  },
  {
    "id": "yildiz-yt-39c-18",
    "name": "Yıldız MDFLAM · Dacron Grey YT_39C · 18 мм",
    "type": "MDFLAM",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_39C",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/dacron-grey-yt-39c"
  },
  {
    "id": "yildiz-yt-z32-18",
    "name": "Yıldız MDFLAM · Merano YT_Z32 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z32",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/merano-yt-z32"
  },
  {
    "id": "yildiz-vt-770-18",
    "name": "Yıldız MDFLAM · Marmo VT_770 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_770",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/marmo-vt-770"
  },
  {
    "id": "yildiz-yt-44a-18",
    "name": "Yıldız MDFLAM · Retro Stone YT_44A · 18 мм",
    "type": "MDFLAM",
    "color": "#deddd9",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_44A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/retro-stone-yt-44a"
  },
  {
    "id": "yildiz-yt-90b-18",
    "name": "Yıldız MDFLAM · Frezya YT_90B · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_90B",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/frezya-yt-90b"
  },
  {
    "id": "yildiz-yt-z39-18",
    "name": "Yıldız MDFLAM · Silves YT_Z39 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z39",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/silves-yt-z39"
  },
  {
    "id": "yildiz-yt-z28-18",
    "name": "Yıldız MDFLAM · Sidon YT_Z28 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z28",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/sidon-yt-z28"
  },
  {
    "id": "yildiz-vt-849-18",
    "name": "Yıldız MDFLAM · Rambla VT_849 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_849",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/rambla-vt-849"
  },
  {
    "id": "yildiz-yt-98a-18",
    "name": "Yıldız MDFLAM · Lagina YT_98A · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_98A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/lagina-yt-98a"
  },
  {
    "id": "yildiz-yt-43a-18",
    "name": "Yıldız MDFLAM · Retro Silver YT_43A · 18 мм",
    "type": "MDFLAM",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_43A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/retro-silver-yt-43a"
  },
  {
    "id": "yildiz-vt-715-18",
    "name": "Yıldız MDFLAM · Irony VT_715 · 18 мм",
    "type": "MDFLAM",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_715",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/irony-vt-715"
  },
  {
    "id": "yildiz-yt-02b-18",
    "name": "Yıldız MDFLAM · Sonata YT_02B · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_02B",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/sonata-yt-02b"
  },
  {
    "id": "yildiz-yt-51a-18",
    "name": "Yıldız MDFLAM · Royal Marble YT_51A · 18 мм",
    "type": "MDFLAM",
    "color": "#deddd9",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_51A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/royal-marble-yt-51a"
  },
  {
    "id": "yildiz-vt-187-18",
    "name": "Yıldız MDFLAM · White Birch VT_187 · 18 мм",
    "type": "MDFLAM",
    "color": "#f0f0eb",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_187",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/white-birch-vt-187"
  },
  {
    "id": "yildiz-vt-925-18",
    "name": "Yıldız MDFLAM · White Oak VT_925 · 18 мм",
    "type": "MDFLAM",
    "color": "#f0f0eb",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_925",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/white-oak-vt-925"
  },
  {
    "id": "yildiz-yt-19d-18",
    "name": "Yıldız MDFLAM · Liberta YT_19D · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_19D",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/liberta-yt-19d"
  },
  {
    "id": "yildiz-vt-059-18",
    "name": "Yıldız MDFLAM · Maple VT_059 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_059",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/maple-vt-059"
  },
  {
    "id": "yildiz-vt-292-18",
    "name": "Yıldız MDFLAM · Artemis VT_292 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_292",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/artemis-vt-292"
  },
  {
    "id": "yildiz-vt-202-18",
    "name": "Yıldız MDFLAM · New Oak VT_202 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_202",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/new-oak-vt-202"
  },
  {
    "id": "yildiz-vt-15a-18",
    "name": "Yıldız MDFLAM · Vega VT_15A · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_15A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/vega-vt-15a"
  },
  {
    "id": "yildiz-vt-029-18",
    "name": "Yıldız MDFLAM · Ozigo VT_029 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_029",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/ozigo-vt-029"
  },
  {
    "id": "yildiz-yt-z33-18",
    "name": "Yıldız MDFLAM · Budva YT_Z33 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z33",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/budva-yt-z33"
  },
  {
    "id": "yildiz-vt-293-18",
    "name": "Yıldız MDFLAM · Atlantis VT_293 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_293",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/atlantis-vt-293"
  },
  {
    "id": "yildiz-vt-611-18",
    "name": "Yıldız MDFLAM · Uludag Oak VT_611 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_611",
    "sourceUrl": "https://www.yildizentegre.com/en/products/panel"
  },
  {
    "id": "yildiz-vt-408-18",
    "name": "Yıldız MDFLAM · Sonoma VT_408 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_408",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/sonoma-vt-408"
  },
  {
    "id": "yildiz-vt-450-18",
    "name": "Yıldız MDFLAM · Grey Sonoma VT_450 · 18 мм",
    "type": "MDFLAM",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_450",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/grey-sonoma-vt-450"
  },
  {
    "id": "yildiz-yt-49a-18",
    "name": "Yıldız MDFLAM · Authentic Oak YT_49A · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_49A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/authentic-oak-yt-49a"
  },
  {
    "id": "yildiz-vt-539-18",
    "name": "Yıldız MDFLAM · Sapphire Oak VT_539 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_539",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/sapphire-oak-vt-539"
  },
  {
    "id": "yildiz-vt-203-18",
    "name": "Yıldız MDFLAM · Morgana Cherry VT_203 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_203",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/morgana-cherry-vt-203"
  },
  {
    "id": "yildiz-vt-665-18",
    "name": "Yıldız MDFLAM · Taurus Oak VT_665 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_665",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/taurus-oak-vt-665"
  },
  {
    "id": "yildiz-vt-13a-18",
    "name": "Yıldız MDFLAM · Carina VT_13A · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_13A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/carina-vt-13a"
  },
  {
    "id": "yildiz-vt-673-18",
    "name": "Yıldız MDFLAM · Legnano VT_673 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_673",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/legnano-vt-673"
  },
  {
    "id": "yildiz-yt-97b-18",
    "name": "Yıldız MDFLAM · Moso YT_97B · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_97B",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/moso-yt-97b"
  },
  {
    "id": "yildiz-yt-32c-18",
    "name": "Yıldız MDFLAM · Senza YT_32C · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_32C",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/senza-yt-32c"
  },
  {
    "id": "yildiz-yt-z29-18",
    "name": "Yıldız MDFLAM · Braga YT_Z29 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z29",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/braga-yt-z29"
  },
  {
    "id": "yildiz-yt-61a-18",
    "name": "Yıldız MDFLAM · Exotic Oak YT_61A · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_61A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/exotic-oak-yt-61a"
  },
  {
    "id": "yildiz-vt-09a-18",
    "name": "Yıldız MDFLAM · Dorado VT_09A · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_09A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/dorado-vt-09a"
  },
  {
    "id": "yildiz-yt-z38-18",
    "name": "Yıldız MDFLAM · Lapad YT_Z38 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z38",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/lapad-yt-z38"
  },
  {
    "id": "yildiz-yt-77a-18",
    "name": "Yıldız MDFLAM · Dore YT_77A · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_77A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/dore-yt-77a"
  },
  {
    "id": "yildiz-vt-274-18",
    "name": "Yıldız MDFLAM · Belly VT_274 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_274",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/belly-vt-274"
  },
  {
    "id": "yildiz-vt-681-18",
    "name": "Yıldız MDFLAM · Detroit VT_681 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_681",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/detroit-vt-681"
  },
  {
    "id": "yildiz-yt-z30-18",
    "name": "Yıldız MDFLAM · Mantova YT_Z30 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z30",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/mantova-yt-z30"
  },
  {
    "id": "yildiz-vt-657-18",
    "name": "Yıldız MDFLAM · Atlantic Pine VT_657 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_657",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/atlantic-pine-vt-657"
  },
  {
    "id": "yildiz-vt-323-18",
    "name": "Yıldız MDFLAM · Bamboo VT_323 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_323",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/bamboo-vt-323"
  },
  {
    "id": "yildiz-vt-084-18",
    "name": "Yıldız MDFLAM · Teak VT_084 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_084",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/teak-vt-084"
  },
  {
    "id": "yildiz-vt-810-18",
    "name": "Yıldız MDFLAM · Kaman Walnut VT_810 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_810",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/kaman-walnut-vt-810"
  },
  {
    "id": "yildiz-vt-275-18",
    "name": "Yıldız MDFLAM · Avanos Walnut VT_275 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_275",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/avanos-walnut-vt-275"
  },
  {
    "id": "yildiz-yt-54a-18",
    "name": "Yıldız MDFLAM · Brazilian Walnut YT_54A · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_54A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/panel"
  },
  {
    "id": "yildiz-vt-710-18",
    "name": "Yıldız MDFLAM · Montana VT_710 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_710",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/montana-vt-710"
  },
  {
    "id": "yildiz-vt-14a-18",
    "name": "Yıldız MDFLAM · Mensa VT_14A · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_14A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/mensa-vt-14a"
  },
  {
    "id": "yildiz-vt-859-18",
    "name": "Yıldız MDFLAM · Caspian VT_859 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_859",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/caspian-vt-859"
  },
  {
    "id": "yildiz-vt-565-18",
    "name": "Yıldız MDFLAM · Caucasian Oak VT_565 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_565",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/caucasian-oak-vt-565"
  },
  {
    "id": "yildiz-yt-60a-18",
    "name": "Yıldız MDFLAM · Hamilton YT_60A · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_60A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/hamilton-yt-60a"
  },
  {
    "id": "yildiz-vt-053-18",
    "name": "Yıldız MDFLAM · Nile Walnut VT_053 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_053",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/nile-walnut-vt-053"
  },
  {
    "id": "yildiz-vt-188-18",
    "name": "Yıldız MDFLAM · Victorian Walnut VT_188 · 18 мм",
    "type": "MDFLAM",
    "color": "#5a3d28",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_188",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/victorian-walnut-vt-188"
  },
  {
    "id": "yildiz-vt-302-18",
    "name": "Yıldız MDFLAM · Moire Walnut VT_302 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_302",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/moire-walnut-vt-302"
  },
  {
    "id": "yildiz-vt-261-18",
    "name": "Yıldız MDFLAM · Soke Walnut VT_261 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_261",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/soke-walnut-vt-261"
  },
  {
    "id": "yildiz-vt-674-18",
    "name": "Yıldız MDFLAM · Navaro VT_674 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_674",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/navaro-vt-674"
  },
  {
    "id": "yildiz-vt-509-18",
    "name": "Yıldız MDFLAM · Rustic Oak VT_509 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_509",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/rustic-oak-vt-509"
  },
  {
    "id": "yildiz-yt-z34-18",
    "name": "Yıldız MDFLAM · Balos YT_Z34 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z34",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/balos-yt-z34"
  },
  {
    "id": "yildiz-yt-04b-18",
    "name": "Yıldız MDFLAM · Lumiere YT_04B · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_04B",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/lumiere-yt-04b"
  },
  {
    "id": "yildiz-vt-017-18",
    "name": "Yıldız MDFLAM · Beech VT_017 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_017",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/beech-vt-017"
  },
  {
    "id": "yildiz-vt-014-18",
    "name": "Yıldız MDFLAM · Walnut VT_014 · 18 мм",
    "type": "MDFLAM",
    "color": "#a98257",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_014",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/walnut-vt-014"
  },
  {
    "id": "yildiz-vt-254-18",
    "name": "Yıldız MDFLAM · Palisander VT_254 · 18 мм",
    "type": "MDFLAM",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_254",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/palisander-vt-254"
  },
  {
    "id": "yildiz-yt-z40-18",
    "name": "Yıldız MDFLAM · Lindos YT_Z40 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z40",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/lindos-yt-z40"
  },
  {
    "id": "yildiz-vt-518-18",
    "name": "Yıldız MDFLAM · New Wenge VT_518 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": true,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "VT_518",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/new-wenge-vt-518"
  },
  {
    "id": "yildiz-yt-z35-18",
    "name": "Yıldız MDFLAM · Arno YT_Z35 · 18 мм",
    "type": "MDFLAM",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 2100,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "YT_Z35",
    "sourceUrl": "https://www.yildizentegre.com/en/products/melamine-faced-mdfpb/arno-yt-z35"
  },
  {
    "id": "yildiz-mat-10m-18",
    "name": "Yıldız Kapak Panel · Terra Rosso MAT_10M · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#7d383b",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_10M",
    "sourceUrl": "https://www.yildizentegre.com/en/products/panel"
  },
  {
    "id": "yildiz-mat-10k-18",
    "name": "Yıldız Kapak Panel · Pure Marble MAT_10K · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#deddd9",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_10K",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/pure-marble-mat-10k"
  },
  {
    "id": "yildiz-mat-10p-18",
    "name": "Yıldız Kapak Panel · Polar Stone MAT_10P · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#deddd9",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_10P",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/polar-stone-mat-10p"
  },
  {
    "id": "yildiz-mat-10l-18",
    "name": "Yıldız Kapak Panel · Ash Concrete MAT_10L · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_10L",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/ash-concrete-mat-10l"
  },
  {
    "id": "yildiz-mat-63c-18",
    "name": "Yıldız Kapak Panel · Canyon Beige MAT_63C · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_63C",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/canyon-beige-mat-63c"
  },
  {
    "id": "yildiz-mat-62c-18",
    "name": "Yıldız Kapak Panel · Canyon Grey MAT_62C · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_62C",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/canyon-grey-mat-62c"
  },
  {
    "id": "yildiz-mat-50c-18",
    "name": "Yıldız Kapak Panel · Grey Line MAT_50C · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_50C",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/grey-line-mat-50c"
  },
  {
    "id": "yildiz-mat-z47-18",
    "name": "Yıldız Kapak Panel · Doris MAT_Z47 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_Z47",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/doris-mat-z47"
  },
  {
    "id": "yildiz-mat-z44-18",
    "name": "Yıldız Kapak Panel · Tess MAT_Z44 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_Z44",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/tess-mat-z44"
  },
  {
    "id": "yildiz-mat-z43-18",
    "name": "Yıldız Kapak Panel · Naro MAT_Z43 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_Z43",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/naro-mat-z43"
  },
  {
    "id": "yildiz-mat-z50-18",
    "name": "Yıldız Kapak Panel · Callisto MAT_Z50 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_Z50",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/callisto-mat-z50"
  },
  {
    "id": "yildiz-mat-z51-18",
    "name": "Yıldız Kapak Panel · Nove MAT_Z51 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_Z51",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/nove-mat-z51"
  },
  {
    "id": "yildiz-mat-711-18",
    "name": "Yıldız Kapak Panel · Concrete Grey MAT_711 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_711",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/concrete-grey-mat-711"
  },
  {
    "id": "yildiz-mat-z49-18",
    "name": "Yıldız Kapak Panel · Ceres MAT_Z49 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_Z49",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/ceres-mat-z49"
  },
  {
    "id": "yildiz-mat-81a-18",
    "name": "Yıldız Kapak Panel · Antique Bronze MAT_81A · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#b89758",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_81A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/antique-bronze-mat-81a"
  },
  {
    "id": "yildiz-mat-771-18",
    "name": "Yıldız Kapak Panel · Natural White MAT_771 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#f0f0eb",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_771",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/natural-white-matt-mat-771"
  },
  {
    "id": "yildiz-mat-718-18",
    "name": "Yıldız Kapak Panel · Light Beige MAT_718 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_718",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/light-beige-matt-mat-718"
  },
  {
    "id": "yildiz-mat-88a-18",
    "name": "Yıldız Kapak Panel · Light Grey MAT_88A · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c4c6c5",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_88A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/light-grey-mat-88a"
  },
  {
    "id": "yildiz-mat-28b-18",
    "name": "Yıldız Kapak Panel · Soft Grey MAT_28B · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c4c6c5",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_28B",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/soft-grey-mat-28b"
  },
  {
    "id": "yildiz-mat-53c-18",
    "name": "Yıldız Kapak Panel · Powder Beige MAT_53C · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_53C",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/powder-beige-matt-mat-53c"
  },
  {
    "id": "yildiz-mat-67c-18",
    "name": "Yıldız Kapak Panel · Pastel Beige MAT_67C · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_67C",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/pastel-beige-matt-mat-67c"
  },
  {
    "id": "yildiz-mat-54c-18",
    "name": "Yıldız Kapak Panel · Modern Grey MAT_54C · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_54C",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/modern-grey-matt-mat-54c"
  },
  {
    "id": "yildiz-mat-85a-18",
    "name": "Yıldız Kapak Panel · Cool Grey MAT_85A · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c4c6c5",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_85A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/cool-grey-mat-85a"
  },
  {
    "id": "yildiz-mat-56c-18",
    "name": "Yıldız Kapak Panel · Chrome Grey MAT_56C · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_56C",
    "sourceUrl": "https://www.yildizentegre.com/en/products/panel"
  },
  {
    "id": "yildiz-mat-538-18",
    "name": "Yıldız Kapak Panel · Sand Beige MAT_538 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_538",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/mat-sand-beige-mat-538"
  },
  {
    "id": "yildiz-mat-237-18",
    "name": "Yıldız Kapak Panel · Grey MAT_237 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_237",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/mat-grey-mat-237"
  },
  {
    "id": "yildiz-mat-86a-18",
    "name": "Yıldız Kapak Panel · Spanish Beige MAT_86A · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_86A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/spanish-beige-mat-86a"
  },
  {
    "id": "yildiz-mat-z53-18",
    "name": "Yıldız Kapak Panel · İyon MAT_Z53 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_Z53",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/iyon-mat-z53"
  },
  {
    "id": "yildiz-mat-59c-18",
    "name": "Yıldız Kapak Panel · Nile Green MAT_59C · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#5d7362",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_59C",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/nile-green-mat-59c"
  },
  {
    "id": "yildiz-mat-61c-18",
    "name": "Yıldız Kapak Panel · Pastel Blue MAT_61C · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#4b6982",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_61C",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/pastel-blue-mat-61c"
  },
  {
    "id": "yildiz-mat-z55-18",
    "name": "Yıldız Kapak Panel · Leda MAT_Z55 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_Z55",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/leda-mat-z55"
  },
  {
    "id": "yildiz-mat-35b-18",
    "name": "Yıldız Kapak Panel · Night Blue MAT_35B · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#4b6982",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_35B",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/night-blue-mat-35b"
  },
  {
    "id": "yildiz-mat-921-18",
    "name": "Yıldız Kapak Panel · Basalt Grey MAT_921 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#4a4d4f",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_921",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/basalt-grey-mat-921"
  },
  {
    "id": "yildiz-mat-551-18",
    "name": "Yıldız Kapak Panel · Lava MAT_551 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_551",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/mat-lava-mat-551"
  },
  {
    "id": "yildiz-mat-15d-18",
    "name": "Yıldız Kapak Panel · Cosmic Fume MAT_15D · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#4a4d4f",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_15D",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/cosmic-fume-mat-15d"
  },
  {
    "id": "yildiz-mat-429-18",
    "name": "Yıldız Kapak Panel · Fume MAT_429 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#4a4d4f",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_429",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/mat-fume-mat-429"
  },
  {
    "id": "yildiz-mat-z56-18",
    "name": "Yıldız Kapak Panel · Elara MAT_Z56 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_Z56",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/elara-mat-z56"
  },
  {
    "id": "yildiz-mat-037-18",
    "name": "Yıldız Kapak Panel · Black MAT_037 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#303433",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_037",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/mat-black-mat-037"
  },
  {
    "id": "yildiz-mat-z46-18",
    "name": "Yıldız Kapak Panel · Davida MAT_Z46 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_Z46",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/davida-mat-z46"
  },
  {
    "id": "yildiz-mat-z45-18",
    "name": "Yıldız Kapak Panel · Kepler MAT_Z45 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_Z45",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/kepler-mat-z45"
  },
  {
    "id": "yildiz-mat-91a-18",
    "name": "Yıldız Kapak Panel · Latte Leather MAT_91A · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_91A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/latte-leather-mat-91a"
  },
  {
    "id": "yildiz-mat-z54-18",
    "name": "Yıldız Kapak Panel · Gravity MAT_Z54 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_Z54",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/gravity-mat-z54"
  },
  {
    "id": "yildiz-mat-z52-18",
    "name": "Yıldız Kapak Panel · Apollo MAT_Z52 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_Z52",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/apollo-mat-z52"
  },
  {
    "id": "yildiz-mat-z48-18",
    "name": "Yıldız Kapak Panel · Halley MAT_Z48 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_Z48",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/halley-mat-z48"
  },
  {
    "id": "yildiz-mat-80a-18",
    "name": "Yıldız Kapak Panel · Antique Gold MAT_80A · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#b89758",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "MAT_80A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/antique-gold-mat-80a"
  },
  {
    "id": "yildiz-hg-771-18",
    "name": "Yıldız Kapak Panel · Natural White HG_771 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#f0f0eb",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_771",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/natural-white-hg-771"
  },
  {
    "id": "yildiz-hg-718-18",
    "name": "Yıldız Kapak Panel · Light Beige HG_718 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_718",
    "sourceUrl": "https://www.yildizentegre.com/en/products/panel"
  },
  {
    "id": "yildiz-hg-631-18",
    "name": "Yıldız Kapak Panel · Bianco HG_631 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#f0f0eb",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_631",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/bianco-hg-631"
  },
  {
    "id": "yildiz-hg-144-18",
    "name": "Yıldız Kapak Panel · HG Cream HG_144 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#f1ede2",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_144",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/hg-cream-hg-144"
  },
  {
    "id": "yildiz-hg-53c-18",
    "name": "Yıldız Kapak Panel · Powder Beige HG_53C · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_53C",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/powder-beige-hg-53c"
  },
  {
    "id": "yildiz-hg-67c-18",
    "name": "Yıldız Kapak Panel · Pastel Beige HG_67C · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_67C",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/pastel-beige-hg-67c"
  },
  {
    "id": "yildiz-hg-278-18",
    "name": "Yıldız Kapak Panel · Cappuccino HG_278 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_278",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/hg-cappuccino-hg-278"
  },
  {
    "id": "yildiz-hg-910-18",
    "name": "Yıldız Kapak Panel · Ice Grey HG_910 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_910",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/ice-grey-hg-910"
  },
  {
    "id": "yildiz-hg-54c-18",
    "name": "Yıldız Kapak Panel · Modern Grey HG_54C · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_54C",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/modern-grey-hg-54c"
  },
  {
    "id": "yildiz-hg-28b-18",
    "name": "Yıldız Kapak Panel · Soft Grey HG_28B · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#c4c6c5",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_28B",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/soft-grey-hg-28b"
  },
  {
    "id": "yildiz-hg-56c-18",
    "name": "Yıldız Kapak Panel · Chrome Grey HG_56C · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_56C",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/chrome-grey-hg-56c"
  },
  {
    "id": "yildiz-hg-538-18",
    "name": "Yıldız Kapak Panel · Sand Beige HG_538 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_538",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/hg-sand-beige-hg-538"
  },
  {
    "id": "yildiz-hg-237-18",
    "name": "Yıldız Kapak Panel · Grey HG_237 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_237",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/hg-grey-hg-237"
  },
  {
    "id": "yildiz-hg-52c-18",
    "name": "Yıldız Kapak Panel · Ruby HG_52C · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#7d383b",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_52C",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/ruby-hg-52c"
  },
  {
    "id": "yildiz-hg-921-18",
    "name": "Yıldız Kapak Panel · Basalt Grey HG_921 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#4a4d4f",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_921",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/basalt-grey-hg-921"
  },
  {
    "id": "yildiz-hg-551-18",
    "name": "Yıldız Kapak Panel · Lava HG_551 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_551",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/hg-lava-hg-551"
  },
  {
    "id": "yildiz-hg-429-18",
    "name": "Yıldız Kapak Panel · Fume HG_429 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#4a4d4f",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_429",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/hg-fume-hg-429"
  },
  {
    "id": "yildiz-hg-121-18",
    "name": "Yıldız Kapak Panel · Anthracite Grey HG_121 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#4a4d4f",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_121",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/hg-anthracite-grey-hg-121"
  },
  {
    "id": "yildiz-hg-037-18",
    "name": "Yıldız Kapak Panel · Black HG_037 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#303433",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_037",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/hg-black-hg-037"
  },
  {
    "id": "yildiz-hg-92a-18",
    "name": "Yıldız Kapak Panel · White Marble HG_92A · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#f0f0eb",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_92A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/white-marble-hg-92a"
  },
  {
    "id": "yildiz-hg-400-18",
    "name": "Yıldız Kapak Panel · Ecru White HG_400 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#f0f0eb",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_400",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/ecru-white-hg-400"
  },
  {
    "id": "yildiz-hg-402-18",
    "name": "Yıldız Kapak Panel · Ecru Cream HG_402 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#f1ede2",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_402",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/ecru-cream-hg-402"
  },
  {
    "id": "yildiz-hg-419-18",
    "name": "Yıldız Kapak Panel · Honey Bubble HG_419 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#c5b38e",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_419",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/honey-bubble-hg-419"
  },
  {
    "id": "yildiz-hg-24b-18",
    "name": "Yıldız Kapak Panel · Ecru New Grey HG_24B · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_24B",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/ecru-new-grey-hg-24b"
  },
  {
    "id": "yildiz-hg-403-18",
    "name": "Yıldız Kapak Panel · Ecru Anthracite HG_403 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#4a4d4f",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "HG_403",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/hg-ecru-anthracite-hg-403"
  },
  {
    "id": "yildiz-l-acr-mat-263-18",
    "name": "Yıldız Kapak Panel · Snow White L_ACR_MAT_263 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#f0f0eb",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "L_ACR_MAT_263",
    "sourceUrl": "https://www.yildizentegre.com/en/products/panel"
  },
  {
    "id": "yildiz-l-acr-mat-068-18",
    "name": "Yıldız Kapak Panel · White L_ACR_MAT_068 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#f0f0eb",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "L_ACR_MAT_068",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/luxury-acrylic-matt-white-l-acr-mat-068"
  },
  {
    "id": "yildiz-l-acr-mat-144-18",
    "name": "Yıldız Kapak Panel · Cream L_ACR_MAT_144 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#f1ede2",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "L_ACR_MAT_144",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/luxury-acrylic-matt-cream-l-acr-mat-144"
  },
  {
    "id": "yildiz-l-acr-mat-88a-18",
    "name": "Yıldız Kapak Panel · Light Grey L_ACR_MAT_88A · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#c4c6c5",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "L_ACR_MAT_88A",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/luxury-acrylic-matt-light-grey-l-acr-mat-88a"
  },
  {
    "id": "yildiz-l-acr-mat-465-18",
    "name": "Yıldız Kapak Panel · Ecru Grey L_ACR_MAT_465 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "L_ACR_MAT_465",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/luxury-acrylic-matt-ecru-grey-l-acr-mat-465"
  },
  {
    "id": "yildiz-l-acr-mat-237-18",
    "name": "Yıldız Kapak Panel · Grey L_ACR_MAT_237 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "L_ACR_MAT_237",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/luxury-acrylic-matt-grey-l-acr-mat-237"
  },
  {
    "id": "yildiz-l-acr-mat-285-18",
    "name": "Yıldız Kapak Panel · Dark Grey L_ACR_MAT_285 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#4a4d4f",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "L_ACR_MAT_285",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/luxury-acrylic-matt-dark-grey-l-acr-mat-285"
  },
  {
    "id": "yildiz-l-acr-mat-037-18",
    "name": "Yıldız Kapak Panel · Black L_ACR_MAT_037 · 18 мм",
    "type": "MDF с матовым покрытием",
    "color": "#303433",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "L_ACR_MAT_037",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/luxury-acrylic-matt-black-l-acr-mat-037"
  },
  {
    "id": "yildiz-u-acr-263-18",
    "name": "Yıldız Kapak Panel · Snow White U_ACR_263 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#f0f0eb",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "U_ACR_263",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/ultra-acrylic-snow-white-u-acr-263"
  },
  {
    "id": "yildiz-u-acr-068-18",
    "name": "Yıldız Kapak Panel · White U_ACR_068 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#f0f0eb",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "U_ACR_068",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/ultra-acrylic-white-u-acr-068"
  },
  {
    "id": "yildiz-u-acr-144-18",
    "name": "Yıldız Kapak Panel · Cream U_ACR_144 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#f1ede2",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "U_ACR_144",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/ultra-acrylic-cream-u-acr-144"
  },
  {
    "id": "yildiz-u-acr-a05-18",
    "name": "Yıldız Kapak Panel · Cashmere U_ACR_A05 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "U_ACR_A05",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/ultra-acrylic-cashmere-u-acr-a05"
  },
  {
    "id": "yildiz-u-acr-278-18",
    "name": "Yıldız Kapak Panel · Cappuccino U_ACR_278 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "U_ACR_278",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/ultra-acrylic-cappuccino-u-acr-278"
  },
  {
    "id": "yildiz-u-acr-237-18",
    "name": "Yıldız Kapak Panel · Grey U_ACR_237 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "U_ACR_237",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/ultra-acrylic-grey-u-acr-237"
  },
  {
    "id": "yildiz-u-acr-285-18",
    "name": "Yıldız Kapak Panel · Dark Grey U_ACR_285 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#4a4d4f",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "U_ACR_285",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/ultra-acrylic-dark-grey-u-acr-285"
  },
  {
    "id": "yildiz-u-acr-465-18",
    "name": "Yıldız Kapak Panel · Ecru Grey U_ACR_465 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "U_ACR_465",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/ultra-acrylic-ecru-grey-u-acr-465"
  },
  {
    "id": "yildiz-u-acr-723-18",
    "name": "Yıldız Kapak Panel · Ecru Beige U_ACR_723 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#f1ede2",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "U_ACR_723",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/ultra-acrylic-ecru-beige-u-acr-723"
  },
  {
    "id": "yildiz-u-acr-403-18",
    "name": "Yıldız Kapak Panel · Ecru Anthracite U_ACR_403 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#4a4d4f",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "U_ACR_403",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/ultra-acrylic-ecru-anthracite-u-acr-403"
  },
  {
    "id": "yildiz-l-acr-263-18",
    "name": "Yıldız Kapak Panel · Snow White L_ACR_263 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#f0f0eb",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "L_ACR_263",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/luxury-acrylic-snow-white-l-acr-263"
  },
  {
    "id": "yildiz-l-acr-068-18",
    "name": "Yıldız Kapak Panel · White L_ACR_068 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#f0f0eb",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "L_ACR_068",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/luxury-acrylic-white-l-acr-068"
  },
  {
    "id": "yildiz-l-acr-144-18",
    "name": "Yıldız Kapak Panel · Cream L_ACR_144 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#f1ede2",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "L_ACR_144",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/luxury-acrylic-cream-l-acr-144"
  },
  {
    "id": "yildiz-l-acr-a05-18",
    "name": "Yıldız Kapak Panel · Cashmere L_ACR_A05 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "L_ACR_A05",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/luxury-acrylic-cashmere-l-acr-a05"
  },
  {
    "id": "yildiz-l-acr-278-18",
    "name": "Yıldız Kapak Panel · Cappuccino L_ACR_278 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#d5cbba",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "L_ACR_278",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/luxury-acrylic-cappuccino-l-acr-278"
  },
  {
    "id": "yildiz-l-acr-237-18",
    "name": "Yıldız Kapak Panel · Grey L_ACR_237 · 18 мм",
    "type": "MDF с глянцевым покрытием",
    "color": "#9ca1a3",
    "thickness": 18,
    "sheetWidth": 1220,
    "sheetHeight": 2800,
    "grain": false,
    "edgeBand": 1,
    "manufacturer": "Yıldız Entegre",
    "decorCode": "L_ACR_237",
    "sourceUrl": "https://www.yildizentegre.com/en/products/front-panel/luxury-acrylic-grey-l-acr-237"
  }
];
